In [20]:
import numpy as np

# Create a 2-dimensional array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Flatten the array to a 1-dimensional array 
flattened_array = arr.flatten()

print("Flattened Array:")
print(flattened_array)


Flattened Array:
[1 2 3 4 5 6]


In [21]:
# Create a 1-dimensional array
arr = np.array([1, 2, 3])

# Expand the dimensions of the array
expanded_array = np.expand_dims(arr, axis=1)

# Print the result
print("Expanded Array:")
print(expanded_array)


Expanded Array:
[[1]
 [2]
 [3]]


In [22]:
# Create a 1-dimensional array with size 1 in one of the dimensions
arr = np.array([[1], [2], [3]]) 

# Squeeze the array to remove the single-dimensional entry
squeezed_array = np.squeeze(arr)

# Print the result
print("Squeezed Array:")
print(squeezed_array)


Squeezed Array:
[1 2 3]


In [23]:
# Create a 1-dimensional array
arr = np.array([1, 2, 3])

# Repeat each element three times
repeated_array = np.repeat(arr, repeats=3)

# Print the result
print("Repeated Array:")
print(repeated_array)


Repeated Array:
[1 1 1 2 2 2 3 3 3]


In [24]:
# Create a 1-dimensional array
arr = np.array([1, 2, 3, 4, 5])

# Roll the elements one position to the right
rolled_array = np.roll(arr, shift=1)

# Print the result
print("Rolled Array:")
print(rolled_array)


Rolled Array:
[5 1 2 3 4]


In [25]:
arr = np.array([1, 2, 3, 4, 5])

# Extract the diagonal elements 
diagonal_elements = np.diag(arr)

# Print the result
print("Diagonal Elements:")
print(diagonal_elements)


Diagonal Elements:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [26]:
arr = np.array(['Prasanjit' , "Roy"])
np.char.upper(arr) 

array(['PRASANJIT', 'ROY'], dtype='<U9')

In [27]:
# Create an array
arr = np.array([3, 1, 2, 5, 4])

# Sort the array in ascending order 
sorted_arr = np.sort(arr)
print("Sorted Array:")
print(sorted_arr)
np.searchsorted(arr ,30)


Sorted Array:
[1 2 3 4 5]


5

In [28]:
# Create an array
arr = np.array([3, 1, 2, 5, 4])

# Find the index of the maximum value
max_index = np.argmax(arr)
print("Index of Maximum Value:", max_index)

# Find the index of the minimum value
min_index = np.argmin(arr)
print("Index of Minimum Value:", min_index) 

Index of Maximum Value: 3
Index of Minimum Value: 1


In [29]:
# Create an array
arr = np.array([3, 1, 0, 5, 0, 4])

# Count the number of non-zero elements
count_nonzero = np.count_nonzero(arr)
print("Number of Non-Zero Elements:", count_nonzero)


Number of Non-Zero Elements: 4


In [30]:
arr = np.array([3, 1, 0, 5, 0, 4])
np.where(arr > 3)

(array([3, 5]),)