In [34]:
import numpy as np
mylist = [1, 2, 3, 4]
array = np.array(mylist)
print(array)
print(type(array))


[1 2 3 4]
<class 'numpy.ndarray'>


In [35]:
np.array([[1,2] ,[3,4]])


array([[1, 2],
       [3, 4]])

In [36]:
np.asarray(mylist)

array([1, 2, 3, 4])

In [37]:
a = [2,3,4]
np.asanyarray(a)

array([2, 3, 4])

In [38]:
b = np.matrix(mylist)
b
# Array Can Be Convert Into Matrix Its Subset Of Array
# Matrix Cannot Convert Into Array 

matrix([[1, 2, 3, 4]])

In [39]:
# NumPy Copy Example:
# Create an original NumPy array
original_array = np.array([1, 2, 3, 4, 5]) 

# Create a copy of the original array
copied_array = original_array.copy()

# Modify the copied array
copied_array[0] = 100

# Print both arrays
print("Original Array:", original_array)
print("Copied Array:", copied_array)


Original Array: [1 2 3 4 5]
Copied Array: [100   2   3   4   5]


In [40]:
# NumPy View Example:
# Create an original NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Create a view of the original array 
view_array = original_array.view()

# Modify the view array
view_array[0] = 100

# Print both arrays
print("Original Array:", original_array)
print("View Array:", view_array)


Original Array: [100   2   3   4   5]
View Array: [100   2   3   4   5]


In [41]:
# Import the NumPy library and alias it as 'np' for convenience
import numpy as np

# Use np.fromfunction() to create a 3x3 NumPy array based on a specified function.
# In this case, the function is a lambda function that takes two parameters 'i' and 'j',
# representing the row and column indices of the array, respectively.
# The lambda function returns True if 'i' is equal to 'j', and False otherwise.
result = np.fromfunction(lambda i, j: i == j, (3, 3))

# Print the resulting NumPy array
print(result)


[[ True False False]
 [False  True False]
 [False False  True]]


In [42]:
np.fromfunction(lambda i, j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [43]:
# Define a generator expression named 'iterable'
# The generator expression generates the square of each number in the range from 0 to 4 (inclusive)
# The syntax (i*i for i in range(5)) generates square of i for each i in the range 0 to 4.
# The generator expression is not evaluated immediately; it will produce the values on-demand.
iterable = (i*i for i in range(5))

# Create a NumPy array from the 'iterable' using np.fromiter()
# The 'np.fromiter()' function creates a NumPy array from an iterable (in this case, the generator expression).
# The second argument 'float' specifies the data type of the resulting NumPy array as 'float'.
# The generated values from the iterable will be converted to float before creating the array.
result_array = np.fromiter(iterable, int)

# Print the resulting NumPy array
print(result_array)


[ 0  1  4  9 16]


In [46]:
# The 'sep=','' argument specifies that the numbers are separated by commas in the string. 
np.fromstring('4,5' , sep= ',', dtype=int)

array([4, 5])

In [50]:
# Create a 2-dimensional NumPy array
# Here, we are creating a 2x3 array

my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array) 

print("Number of Dimensions:", my_array.ndim) 

print("Total Number of Elements:", my_array.size)

print("Shape of the Array:", my_array.shape)


[[1 2 3]
 [4 5 6]]
Number of Dimensions: 2
Total Number of Elements: 6
Shape of the Array: (2, 3)


In [51]:
import numpy as np

# Create a 3-dimensional NumPy array using nested lists
three_dim_array = np.array([[[1, 2], [3, 4]], 
                            [[5, 6], [7, 8]], 
                            [[9, 10], [11, 12]]])

# Print the 3-dimensional array
print(three_dim_array)

print("Number of Dimensions:", three_dim_array.ndim)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Number of Dimensions: 3


In [54]:
MyArray1 = np.array([(1,45,45) , (23,45,66)])
MyArray2 = np.array([(1.5,45,45) , (23,45,66)])
MyArray3 = np.array([('ROY',45,45) , (23,45,66)])

print(MyArray1.dtype)
print(MyArray2.dtype)
print(MyArray3.dtype) 

#One Data Can Can Change The Other Datas 

int64
float64
<U21


In [64]:
# Create an array using np.arange()
# It will generate values from 0 up to (but not including) 10 with a step size of 2 
# The resulting array will be [0, 2, 4, 6, 8] 
result_array = np.arange(0, 10, 2)
result_array_flot = list(np.arange(0.5, 20.5, 5)) 
# Print the resulting array
print(result_array)
print(result_array_flot) 

# float Cant Perform In Core Python 
my_range = range(50,101)  

# Convert the range object to a list to see the values
print(list(my_range))


[0 2 4 6 8]
[0.5, 5.5, 10.5, 15.5]
[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [66]:
# Create an array using np.linspace()
# It will generate 10 equally spaced values between 1 and 5 (inclusive) 
result_array = np.linspace(1, 5, 10) 

print(result_array)


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [70]:
# Example using np.zeros()
# Create a 1-dimensional array with 5 elements, filled with zeros (default dtype=float64)
zeros_array = np.zeros(5)
print("Zeros Array:")
print(zeros_array) 

# Create a 2-dimensional array with 3 rows and 4 columns, filled with zeros of integer data type
zeros_2d_array = np.zeros((3, 4), dtype=int)
print("\nZeros 2D Array:")
print(zeros_2d_array)

# Example using np.ones()
# Create a 1-dimensional array with 3 elements, filled with ones (default dtype=float64)
ones_array = np.ones(3)
print("\nOnes Array:")
print(ones_array)

# Create a 3-dimensional array with shape (2, 3, 2), filled with ones of integer data type
ones_3d_array = np.ones((2, 3, 2), dtype=int)
print("\nOnes 3D Array:")
print(ones_3d_array)


Zeros Array:
[0. 0. 0. 0. 0.]

Zeros 2D Array:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Ones Array:
[1. 1. 1.]

Ones 3D Array:
[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [74]:
Sum  = np.ones((2,3,2), dtype=int)
Sum + 5 

array([[[6, 6],
        [6, 6],
        [6, 6]],

       [[6, 6],
        [6, 6],
        [6, 6]]])

In [75]:
Into  = np.ones((2,3,2), dtype=int)
Into * 5 

array([[[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]]])

In [77]:
# Example using np.empty()
# Create a 2-dimensional array with shape (3, 4) filled with uninitialized values
empty_array = np.empty((3, 4))
print("Empty Array:")
print(empty_array) 
# The np.empty() function creates a new array with the specified shape, but the content of the array is not initialized.
# The elements of the array can have any random values depending on the memory state when the array is created.
# Use np.empty() when you need an array of a specific shape, but you don't require the initial values to be set. 

Empty Array:
[[1.14081005e-313 0.00000000e+000 1.01855798e-312 9.54898106e-313]
 [1.20953760e-312 1.01855798e-312 1.23075756e-312 1.01855798e-312]
 [1.10343781e-312 9.76118064e-313 1.12465777e-312 1.90979621e-312]]


In [80]:
# Example using np.eye()
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:")
print(identity_matrix)

# The np.eye() function creates an identity matrix, which is a square matrix with ones on the main diagonal and zeros elsewhere.

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [90]:
# Example using np.logspace()
logspace_array = np.logspace(1, 5, 10)


print("Logarithmic Space Array:")
print(logspace_array)


Logarithmic Space Array:
[1.00000000e+01 2.78255940e+01 7.74263683e+01 2.15443469e+02
 5.99484250e+02 1.66810054e+03 4.64158883e+03 1.29154967e+04
 3.59381366e+04 1.00000000e+05]


In [99]:
# Example using random.randn
random_array = np.random.randn(3,4) 
print("Random Array from Standard Normal Distribution:")
print(random_array)


Random Array from Standard Normal Distribution:
[[-0.81787119  0.85489774 -0.62741927  1.20903274]
 [ 1.57552603  0.74517919  0.03871229  0.94781006]
 [-0.57012319  0.76182967 -2.2689599  -0.0288614 ]]


In [100]:
import pandas as pd 
pd.DataFrame(random_array) 

0         1         2         3
0 -0.817871  0.854898 -0.627419  1.209033
1  1.575526  0.745179  0.038712  0.947810
2 -0.570123  0.761830 -2.268960 -0.028861

In [101]:
np.random.rand(3,4)


array([[0.86474544, 0.90819282, 0.07947385, 0.85643072],
       [0.05921113, 0.29983768, 0.46470159, 0.35892216],
       [0.14929236, 0.86181358, 0.39731731, 0.78220289]])

In [102]:
np.random.randint(1,110 , (300,400))

array([[  4,  99, 101, ...,  74,  69, 106],
       [ 37,  96,  14, ...,  33,   3,  12],
       [ 73,  99,  50, ...,  83,  38,  97],
       ...,
       [ 45,  67,  36, ...,  50,  26,  24],
       [ 80,  96,  66, ...,  35,  62,  78],
       [104,  79,  57, ...,  87,  89,  66]])

In [103]:
pd.DataFrame(np.random.randint(1,110 , (300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0      5   97  102   41   93  107    9   98   99   92  ...   80   88   67   
1     78    8   38  104   62  106   20    3   49   73  ...   81   40   62   
2     36   65   37   33   46   70   62  100  107   62  ...   89   52   19   
3     78   85   96   92   50   79   28   76   35   53  ...   64    3   93   
4     72   34   54   36   90   72   73  106   70   76  ...   29   93  106   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   20   98   33   71   56  109   31   67   53   69  ...   47   38   97   
296   72   13   43   42   29   57   25   77   38   16  ...   50   39   49   
297    4   15   61   63   45   83    7   47   24   78  ...   52   26    8   
298  101   85   51  101   43   76   28  104   87  109  ...   53   91   77   
299   75   42   22   96    7   32   46   60    1   74  ...   86   39   24   

     393  394  395  396  397  398  399  
0     28   76   33   95   21   43   28  
1     57   46   30   90   23   19   21  
2     46  101  105   62   59   38   22  
3    106   53   79   58   75   65   33  
4     57   88   22   12   69   77   92  
..   ...  ...  ...  ...  ...  ...  ...  
295   71    6   61   78   13    2   14  
296   76    1   71   69  108   61   79  
297   53   22   64   16   10   73   78  
298   54   47   44   25   84   20   65  
299  104   48   32   88   46   79   75  

[300 rows x 400 columns]

In [104]:
pd.DataFrame(np.random.randint(1,110 , (300,400))).to_csv('Random.csv') 

In [110]:
# Create a 3x4 array filled with random numbers from a uniform distribution in the range [0, 1).
array = np.random.rand(3, 4)
print("Original Array:")
print(array)

# Reshape the array to a new shape of (6, 2)
reshaped_array = array.reshape(6, 2)
print("\nReshaped Array (6 rows, 2 columns):")
print(reshaped_array)


Original Array:
[[0.89873059 0.77075282 0.61718746 0.87998651]
 [0.44015285 0.8486074  0.38824548 0.43561566]
 [0.36506102 0.88768548 0.70428952 0.57300996]]

Reshaped Array (6 rows, 2 columns):
[[0.89873059 0.77075282]
 [0.61718746 0.87998651]
 [0.44015285 0.8486074 ]
 [0.38824548 0.43561566]
 [0.36506102 0.88768548]
 [0.70428952 0.57300996]]


In [114]:
reshaped_array[2:5,1]

array([0.8486074 , 0.43561566, 0.88768548])

In [121]:
OurArray = np.random.randint(1,100 , (5,5))
OurArray 

array([[89, 93, 85, 37, 77],
       [36, 49, 39, 20, 94],
       [ 8, 93, 53, 49, 38],
       [78, 64, 23, 18, 68],
       [39, 68, 37, 27, 71]])

In [122]:
OurArray >50

array([[ True,  True,  True, False,  True],
       [False, False, False, False,  True],
       [False,  True,  True, False, False],
       [ True,  True, False, False,  True],
       [False,  True, False, False,  True]])

In [123]:
OurArray [OurArray >50]

array([89, 93, 85, 77, 94, 93, 53, 78, 64, 68, 68, 71])

In [125]:
OurArray[2:4 , [1,2]] 

array([[93, 53],
       [64, 23]])

In [126]:
A1 = np.random.randint(1,3 , (3,3))
A2 = np.random.randint(1,3 , (3,3)) 
print(A1)
print(A2) 

[[2 1 1]
 [1 2 1]
 [2 1 1]]
[[2 1 2]
 [1 1 2]
 [1 1 1]]


In [128]:
A1+A2

array([[4, 2, 3],
       [2, 3, 3],
       [3, 2, 2]])

In [129]:
A1*A2

array([[4, 1, 2],
       [1, 2, 2],
       [2, 1, 1]])

In [130]:
A1/A2

array([[1. , 1. , 0.5],
       [1. , 2. , 0.5],
       [2. , 1. , 1. ]])

In [132]:
A1 @ A2

array([[6, 4, 7],
       [5, 4, 7],
       [6, 4, 7]])

In [131]:
# Colums Of 1 Matrix And Rows Of 2 Matrix Should Be Euqals For Matrix Multiplication 

# Define two 2x3 matrices as NumPy arrays
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]]) 

# Perform matrix multiplication using np.dot() or @ operator
result_dot = np.dot(matrix1, matrix2)
result_at_operator = matrix1 @ matrix2

# Print the results
print("Matrix Multiplication using np.dot():")
print(result_dot)

print("\nMatrix Multiplication using @ operator:")
print(result_at_operator)


Matrix Multiplication using np.dot():
[[ 58  64]
 [139 154]]

Matrix Multiplication using @ operator:
[[ 58  64]
 [139 154]]


In [133]:
# Broadcasting ----------------------------------------------------------------> 

# Define a 4x4 array filled with zeros 
array = np.zeros((4, 4)) 

# Define a 1-dimensional array 
row = np.array([1, 2, 3, 4])

# Perform element-wise addition using broadcasting
result = array + row

# Print the result
print("Result of Broadcasting:")
print(result)


Result of Broadcasting:
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [134]:
col = np.array([[1,2,3,4]])
col.T 

array([[1],
       [2],
       [3],
       [4]])

In [135]:
col.T + array

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [136]:
MyArray = np.random.randint(1,5 , (3,4))
MyArray

array([[1, 2, 3, 2],
       [3, 3, 1, 4],
       [3, 3, 3, 4]])

In [139]:
np.sqrt(MyArray)

array([[1.        , 1.41421356, 1.73205081, 1.41421356],
       [1.73205081, 1.73205081, 1.        , 2.        ],
       [1.73205081, 1.73205081, 1.73205081, 2.        ]])

In [140]:
# Define an array with some values
ArrayXYZ = np.array([4, 9, 16, 25, 36])

# Calculate the square root of the array elements
result = np.sqrt(ArrayXYZ) 

# Print the result
print("Square Root of the Array:")
print(result) 

Square Root of the Array:
[2. 3. 4. 5. 6.]
